# Generated by Django 5.2.3 on 2025-07-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.CharField(blank=True, max_length=50)),
                ('categorie', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cout_estime', models.FloatField()),
                ('temps_preparation', models.IntegerField()),
                ('instructions', models.TextField()),
                ('ingredients', models.ManyToManyField(to='menuapp.ingredient')),
            ],
        ),
    ]
