# Generated by Django 5.2.3 on 2025-07-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_recette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Légumes', 'Légumes'), ('Fruits', 'Fruits'), ('Viandes', 'Viandes'), ('Produits laitiers', 'Produits laitiers'), ('Épices', 'Épices'), ('Autre', 'Autre')], max_length=50),
        ),
    ]
