# Generated by Django 5.2.3 on 2025-07-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_alter_ingredient_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='lieu',
            field=models.CharField(choices=[('Frigo', 'Frigo'), ('Placard', 'Placard')], default='Frigo', max_length=50),
        ),
    ]
