# Generated by Django 5.2.3 on 2025-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0004_ingredient_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Légumes frais', 'Légumes frais'), ('Fruits frais', 'Fruits frais'), ('Viandes', 'Viandes'), ('Poissons', 'Poissons'), ('Produits laitiers', 'Produits laitiers'), ('Œufs', 'Œufs'), ('Charcuterie', 'Charcuterie'), ('Plats cuisinés', 'Plats cuisinés'), ('Pâtes', 'Pâtes'), ('Riz', 'Riz'), ('Légumineuses', 'Légumineuses'), ('Conserves', 'Conserves'), ('Épices', 'Épices'), ('Céréales', 'Céréales'), ('Biscuits & Snacks', 'Biscuits & Snacks'), ('Huiles & Vinaigres', 'Huiles & Vinaigres'), ('Farine & Sucre', 'Farine & Sucre'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantite',
            field=models.FloatField(),
        ),
    ]
